### ISSUE TITLE
Cannot compile with android 10.0.0

### ISSUE THREAD

**Issue by colbytown** [katzer/cordova-plugin-printer#283]
Cannot compile when using android@10.0.0. I had to upgrade because google play is now requiring we target at least API level 30.

If I uninstall both @ionic-native/printer and cordova-plugin-printer it compiles fine, so this is definitely the culprit.

Below are all the errors that show when running ionic cordova build android --prod --release.

ionic cordova build ios --prod works fine. 

> Task :app:compileReleaseJavaWithJavac FAILED
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:31: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:32: error: package android.support.v4.print does not exist
import android.support.v4.print.PrintHelper;
                               ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:56: error: package PrintHelper does not exist
    private final @NonNull PrintHelper.OnPrintFinishCallback callback;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:68: error: package PrintHelper does not exist
                  @NonNull PrintHelper.OnPrintFinishCallback callback)
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:30: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:31: error: package android.support.v4.print does not exist
import android.support.v4.print.PrintHelper;
                               ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:42: error: package PrintHelper does not exist
    private final @NonNull PrintHelper.OnPrintFinishCallback callback;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:51: error: package PrintHelper does not exist
                @NonNull PrintHelper.OnPrintFinishCallback callback)
                                    ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:25: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:26: error: package android.support.v4.print does not exist
import android.support.v4.print.PrintHelper;
                               ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:38: error: package android.support.v4.print does not exist
import static android.support.v4.print.PrintHelper.ORIENTATION_LANDSCAPE;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:38: error: static import only from classes and interfaces
import static android.support.v4.print.PrintHelper.ORIENTATION_LANDSCAPE;
^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:39: error: package android.support.v4.print does not exist
import static android.support.v4.print.PrintHelper.ORIENTATION_PORTRAIT;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:39: error: static import only from classes and interfaces
import static android.support.v4.print.PrintHelper.ORIENTATION_PORTRAIT;
^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:40: error: package android.support.v4.print does not exist
import static android.support.v4.print.PrintHelper.SCALE_MODE_FILL;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:40: error: static import only from classes and interfaces
import static android.support.v4.print.PrintHelper.SCALE_MODE_FILL;
^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:41: error: package android.support.v4.print does not exist
import static android.support.v4.print.PrintHelper.SCALE_MODE_FIT;
                                      ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:41: error: static import only from classes and interfaces
import static android.support.v4.print.PrintHelper.SCALE_MODE_FIT;
^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:145: error: cannot find symbol
    void decoratePrintHelper (@NonNull PrintHelper printer)
                                       ^
  symbol:   class PrintHelper
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:27: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:28: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:29: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:30: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:30: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:31: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:32: error: package android.support.v4.print does not exist
import android.support.v4.print.PrintHelper;
                               ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/Printer.java:24: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/Printer.java:25: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:47: error: cannot find symbol
    private final @NonNull String jobName;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:53: error: cannot find symbol
    private final @NonNull InputStream input;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:56: error: cannot find symbol
    private final @NonNull PrintHelper.OnPrintFinishCallback callback;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:66: error: cannot find symbol
    PrintAdapter (@NonNull String jobName, int pageCount,
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:67: error: cannot find symbol
                  @NonNull InputStream input,
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintAdapter.java:68: error: cannot find symbol
                  @NonNull PrintHelper.OnPrintFinishCallback callback)
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintAdapter
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:39: error: cannot find symbol
    private final @NonNull PrintDocumentAdapter delegate;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintProxy
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:42: error: cannot find symbol
    private final @NonNull PrintHelper.OnPrintFinishCallback callback;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintProxy
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:50: error: cannot find symbol
    PrintProxy (@NonNull PrintDocumentAdapter adapter,
                 ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintProxy
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintProxy.java:51: error: cannot find symbol
                @NonNull PrintHelper.OnPrintFinishCallback callback)
                 ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintProxy
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:49: error: cannot find symbol
    private final @NonNull JSONObject spec;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:56: error: cannot find symbol
    PrintOptions (@NonNull JSONObject spec)
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:64: error: cannot find symbol
    @NonNull String getJobName()
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:89: error: cannot find symbol
    @NonNull PrintAttributes toPrintAttributes()
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintOptions.java:145: error: cannot find symbol
    void decoratePrintHelper (@NonNull PrintHelper printer)
                               ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintOptions
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:44: error: cannot find symbol
    private final @NonNull PrintIO io;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:51: error: cannot find symbol
    private PrintContent (@NonNull Context ctx) {
                           ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:63: error: cannot find symbol
    static ContentType getContentType (@Nullable String path,
                                        ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:64: error: cannot find symbol
                                       @NonNull Context context)
                                        ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:62: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:77: error: cannot find symbol
    private ContentType getContentType (@Nullable String path)
                                         ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:76: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:136: error: cannot find symbol
    static BufferedInputStream open (@NonNull String path,
                                      ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:137: error: cannot find symbol
                                     @NonNull Context context)
                                      ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:135: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:150: error: cannot find symbol
    private BufferedInputStream open (@NonNull String path)
                                       ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:149: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:183: error: cannot find symbol
    static Bitmap decode (@NonNull String path, @NonNull Context context)
                           ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:183: error: cannot find symbol
    static Bitmap decode (@NonNull String path, @NonNull Context context)
                                                 ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:182: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:196: error: cannot find symbol
    private Bitmap decode (@NonNull String path)
                            ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintContent.java:195: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintContent
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:47: error: cannot find symbol
    private final @NonNull Context context;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:54: error: cannot find symbol
    PrintIO (@NonNull Context ctx)
              ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:68: error: cannot find symbol
    static void copy (@NonNull InputStream input,
                       ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:69: error: cannot find symbol
                      @NonNull OutputStream output) throws IOException
                       ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:90: error: cannot find symbol
    static void close (@NonNull Closeable stream)
                        ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:107: error: cannot find symbol
    InputStream openFile (@NonNull String path)
                           ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:106: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:126: error: cannot find symbol
    Bitmap decodeFile (@NonNull String path)
                        ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:125: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:141: error: cannot find symbol
    InputStream openAsset (@NonNull String path)
                            ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:140: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:160: error: cannot find symbol
    Bitmap decodeAsset (@NonNull String path)
                         ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:159: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:182: error: cannot find symbol
    InputStream openResource (@NonNull String path)
                               ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:181: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:198: error: cannot find symbol
    Bitmap decodeResource (@NonNull String path)
                            ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:197: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:214: error: cannot find symbol
    InputStream openBase64 (@NonNull String path)
                             ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:213: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:230: error: cannot find symbol
    Bitmap decodeBase64 (@NonNull String path)
                          ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:229: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintIO.java:243: error: cannot find symbol
    private int getResId (@NonNull String resPath)
                           ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintIO
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:54: error: cannot find symbol
    private final @NonNull Context context;
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:57: error: cannot find symbol
    private @Nullable WebView view;
             ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:64: error: cannot find symbol
    PrintManager (@NonNull Context context)
                   ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:76: error: cannot find symbol
    boolean canPrintItem (@Nullable String item)
                           ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:91: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:117: error: cannot find symbol
    void print (@Nullable String content, @NonNull JSONObject settings,
                 ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:117: error: cannot find symbol
    void print (@Nullable String content, @NonNull JSONObject settings,
                                           ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:118: error: cannot find symbol
                @NonNull WebView view, @NonNull OnPrintFinishCallback callback)
                 ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:118: error: cannot find symbol
                @NonNull WebView view, @NonNull OnPrintFinishCallback callback)
                                        ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:149: error: cannot find symbol
    private void printHtml (@Nullable String content,
                             ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:150: error: cannot find symbol
                            @NonNull JSONObject settings,
                             ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:151: error: cannot find symbol
                            @NonNull OnPrintFinishCallback callback)
                             ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:163: error: cannot find symbol
    private void printText (@Nullable String content,
                             ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:164: error: cannot find symbol
                            @NonNull JSONObject settings,
                             ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:165: error: cannot find symbol
                            @NonNull OnPrintFinishCallback callback)
                             ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:178: error: cannot find symbol
    private void printContent (@Nullable String content, @NonNull String mimeType,
                                ^
  symbol:   class Nullable
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:178: error: cannot find symbol
    private void printContent (@Nullable String content, @NonNull String mimeType,
                                                          ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager
/platforms/android/app/src/main/java/de/appplant/cordova/plugin/printer/PrintManager.java:179: error: cannot find symbol
                               @NonNull JSONObject settings,
                                ^
  symbol:   class NonNull
  location: class de.appplant.cordova.plugin.printer.PrintManager

**Comment by srinidhirao** [comment]
Any update on this? Currently we have a customer project which is using this plugin. With the latest Cordova-android update, we want to get this working. 

Any pointers how one can update the project to link with latest cordova-android?

Srinidhi

**Comment by carlosg-ordering** [comment]
Same issue here, Any workaround to this issue?

**Comment by cdipierr** [comment]
Hi all, please see a commit I've posted to our repo to resolve this:
https://github.com/mi-corporation/cordova-plugin-printer/commit/091a9b58eddfa3fe7e2be5702f33d6e8b345f714

This is working for me, but I assume breaks building pre-AndroidX. Would be curious if it works for others.

**Comment by baande03** [comment]
@cdipierr - your updates worked for me. Saved me a ton of time, thanks a lot!

**Comment by hburrows** [comment]
Encountered the same compilation issues after upgrading to cordova-android@10.1.1 to meet Google's minimum API requirement.  An update to fix the Android 10 issues would be great per @cdipierr's fork which worked perfectly.

**Comment by anees-synavos** [comment]
did you find any solution ?

**Comment by jainpiyus** [comment]
any solution for this ?

**Comment by blazekyo** [comment]
> Hi all, please see a commit I've posted to our repo to resolve this: [mi-corporation@091a9b5](https://github.com/mi-corporation/cordova-plugin-printer/commit/091a9b58eddfa3fe7e2be5702f33d6e8b345f714)
> 
> This is working for me, but I assume breaks building pre-AndroidX. Would be curious if it works for others.

I've created a node js script to automate the package naming update. 
Just paste it into the ionic project folder (just outside the android folder), then run node scriptFileName.js.

link to download script: https://file.io/TcAqlf9D0WiS

**Comment by JeramieHallyburton** [comment]
You can run "npx jetify" to rename packages to AndroidX

**Comment by Ashish117** [comment]
You can use [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) it will replace any legacy Support Library references.

**Comment by it-steiger** [comment]
> You can use [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) it will replace any legacy Support Library references.

Thanks a lot !!!
