### ISSUE TITLE
Plugin doesnt work work with cordova-ios@4.0.0 or greater.

### ISSUE THREAD

**Issue by BlackRussian** [katzer/cordova-plugin-printer#83]
This function **CDV_IsIPad()** has been removed at cordova-ios@4.0.0 . The function should be replaced with **UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad**

**Comment by dangerdespain** [comment]
👍  This worked for me

**Comment by xavipedrals** [comment]
I changed the function in APPPrinter.m but I still get:

```
Undefined symbols for architecture i386:
  "_CDV_IsIPad", referenced from:
      -[APPPrinter presentPrintController:fromRect:] in APPPrinter.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What am I doing wrong?

**Comment by carlgordon** [comment]
You have to remove the ios platform and add it again

**Comment by katzer** [comment]
Has been fixed
